{% set name = "gcsfs" %}
{% set version = "0.0.4" %}
{% set sha256 = "ea292f63bcfc4d4b3d7744a336775f25df0f22fa1d304803cd0cb4576b943e94" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  noarch: python

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - google-auth
    - google-auth-oauthlib
    - requests

test:
  imports:
    - gcsfs

about:
  home: https://github.com/dask/gcsfs
  license: BSD
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Pythonic file-system interface for Google Cloud Storage'
  doc_url: http://gcsfs.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - martindurant
