{% set name = "gcsfs" %}
{% set version = "0.8.0" %}
{% set sha256 = "6ffb81a93dc4075b056dacb5e8a661b75e79dd2e220538afae94768a6b7be3c6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - google-auth >=1.2
    - google-auth-oauthlib
    - requests
    - decorator
    - fsspec >=0.9.0,<0.10.0
    - aiohttp
    - ujson

test:
  imports:
    - gcsfs

about:
  home: https://github.com/dask/gcsfs
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Pythonic file-system interface for Google Cloud Storage
  doc_url: http://gcsfs.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - martindurant
    - jcrist
    - tomaugspurger
